const ALL_SUPPLY_REQUEST = "ALL_SUPPLY_REQUEST";
const ALL_SUPPLY_SUCCESS = "ALL_SUPPLY_SUCCESS";
const ALL_SUPPLY_FAIL = "ALL_SUPPLY_FAIL";

const SUPPLY_DETAILS_REQUEST = "SUPPLY_DETAILS_REQUEST";
const SUPPLY_DETAILS_SUCCESS = "SUPPLY_DETAILS_SUCCESS";
const SUPPLY_DETAILS_FAIL = "SUPPLY_DETAILS_FAIL";

const USER_SUPPLY_REQUEST = "USER_SUPPLY_REQUEST";
const USER_SUPPLY_SUCCESS = "USER_SUPPLY_SUCCESS";
const USER_SUPPLY_FAIL = "USER_SUPPLY_FAIL";

const CLEAR_ERROR = "CLEAR_ERROR";


const PRICE_FILTER_MIN = 0;
const PRICE_FILTER_MAX = 25000;

export { ALL_SUPPLY_FAIL, ALL_SUPPLY_SUCCESS, ALL_SUPPLY_REQUEST, 
    CLEAR_ERROR, 
    SUPPLY_DETAILS_REQUEST, SUPPLY_DETAILS_SUCCESS, SUPPLY_DETAILS_FAIL,
    USER_SUPPLY_REQUEST ,USER_SUPPLY_SUCCESS, USER_SUPPLY_FAIL,
    PRICE_FILTER_MAX, PRICE_FILTER_MIN
};