const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";

const REGISTER_REQUEST = "REGISTER_REQUEST";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";

const LOADUSER_REQUEST = "LOADUSER_REQUEST";
const LOADUSER_SUCCESS = "LOADUSER_SUCCESS";
const LOADUSER_FAIL = "LOADUSER_FAIL";

const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT_FAIL = "LOGOUT_FAIL";

const UPDATE_AVATAR_REQUEST = "UPDATE_AVATAR_REQUEST";
const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";
const UPDATE_AVATAR_RESET = "UPDATE_AVATAR_RESET";
const UPDATE_AVATAR_FAIL = "UPDATE_AVATAR_FAIL";

const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
const RESET_PASSWORD_RESET = "RESET_PASSWORD_RESET";
const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

const CLEAR_ERROR = "CLEAR_ERROR";

export { LOGIN_REQUEST, LOGIN_SUCCESS , LOGIN_FAIL, CLEAR_ERROR,
     REGISTER_REQUEST, REGISTER_SUCCESS, REGISTER_FAIL,
     LOADUSER_REQUEST, LOADUSER_SUCCESS, LOADUSER_FAIL,
     LOGOUT_SUCCESS, LOGOUT_FAIL,
     UPDATE_AVATAR_REQUEST, UPDATE_AVATAR_SUCCESS, UPDATE_AVATAR_RESET, UPDATE_AVATAR_FAIL,
     UPDATE_PROFILE_REQUEST, UPDATE_PROFILE_SUCCESS, UPDATE_PROFILE_RESET, UPDATE_PROFILE_FAIL,
     UPDATE_PASSWORD_REQUEST, UPDATE_PASSWORD_SUCCESS, UPDATE_PASSWORD_RESET, UPDATE_PASSWORD_FAIL,
     FORGOT_PASSWORD_REQUEST, FORGOT_PASSWORD_SUCCESS, FORGOT_PASSWORD_FAIL,
     RESET_PASSWORD_REQUEST, RESET_PASSWORD_SUCCESS, RESET_PASSWORD_FAIL, RESET_PASSWORD_RESET
 };