const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";

const REGISTER_REQUEST = "REGISTER_REQUEST";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";

const LOADUSER_REQUEST = "LOADUSER_REQUEST";
const LOADUSER_SUCCESS = "LOADUSER_SUCCESS";
const LOADUSER_FAIL = "LOADUSER_FAIL";

const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT_FAIL = "LOGOUT_FAIL";

const CLEAR_ERROR = "CLEAR_ERROR";

export { LOGIN_REQUEST, LOGIN_SUCCESS , LOGIN_FAIL, CLEAR_ERROR,
     REGISTER_REQUEST, REGISTER_SUCCESS, REGISTER_FAIL,
     LOADUSER_REQUEST, LOADUSER_SUCCESS, LOADUSER_FAIL,
     LOGOUT_SUCCESS, LOGOUT_FAIL };